- README.md
Added resources that will help beginners out
> Added useful beginner resources

- README.md
I added resources that will help beginners transition into intermediate flutter devs
> added intermediate resources

- README.md
> added introduction and advanced resources

- README.md
Added sources that I've used myself and found to be really helpful.
> Added some sources

- README.md
Implemented the UI Kit tag with some useful and amazing UI Resources .
Thankyou !.
> Awesome UI Kit Resources

- README.md
Added several machine learning plugins from pub.dev 
TFLite
Speech to text
Firebase ML Vision
Edge detection
> Added Machine Learning plugins to readme

- README.md
Removed FilledStacks & ReactBits that was in the Machine Learning section.
> Removing duplicated YT channels

- README.md
Added GetWidget repository to UI Kit
> Added GetWidget to UI Kit

- README.md
I added firebase resources. It will help people starting out with Firebase.
> Added Firebase Resources

- README.md
Flutter hook is a useful library that reduces the hassles of boilerplate codes of animation and stateful widget. They are an alternative to stateful widget.
> Added Flutter Hook State management

- README.md
It's a growing channel whose videos are really great for beginners. He also shares ideas and tips for becoming a good programmer along the way.
> Added an youtube channel

- README.md
> Revert "Added a new youtube channel"

- README.md
RiverPod is new state management technique by Remi Rousselet.
Reso coder is provided an intermediate course for a flutter by Matt Rešetár.
> RiverPod and ResoCoder

- README.md
So, I Implemented the **Wonderful Animation Plugin's** Section.
Thankyou !.
> Implemented Wonderful Animation Plugins Section

- README.md
Added one more Youtube Channel . This repo is great will feel lucky to be a contributor of it.
> Youtube Channel 

- README.md
UI
* Intro Slider
* Rating Bar
Yt cannel
* Marcus Ng
> Added UI and YT Channels

- README.md
Added new resources for Flutter.
> Added Flutter & Firebase app building tutoria playlist

- README.md
Added a youtube channel which wasnt mentioned in the read me and is a channel which teaches complex concepts in a simple manner.
> Added easy approach youtube channel

- README.md
> Revert 19 main

- README.md
Add reference app category recommended in flutter officiail Website
> Add reference app category

- README.md
I added two new useful YouTube channels along with a useful video from a YouTube Channel!
> Add new YouTube channels

- README.md
Please do accept my contribution. Thank you. Let me know if some changes are to be made.
> Useful Blogs/Websites update

- README.md
Practical Flutter is an amazing book with clear examples and easy explanations of them
> Add Practical Flutter to Books section

- README.md
AWS Amplify is an end-to-end solution that enables mobile and front-end web developers to build and deploy secure, scalable full-stack applications, powered by AWS
> AWS Amplify for Flutter

- README.md
> Added a project link to the repo 

- README.md
This guide provides a comprehensive and intuitive introduction to all of the basics of flutter. It includes installation, the basics of dart, the basics of flutter widgets and architecture, best practices, firebase, and an example project. Links are also provided to useful resources like youtube channels and more.
> Add beginner guide to Introduction

- README.md
Added Tadas petra youtube channel
> updated readme file with YT channel
